### ISSUE TITLE
How to Revert VS2019 to Trial?

### ISSUE THREAD

**Issue by ChthonVII** [beatcracker/VSCELicense#20]
A couple years ago, I did something foolish. Rather than search for a tool like this one, I created a throwaway hotmail account to register VS2019. Fast forward to yesterday and VS informs me that microsoft has suspended my throwaway account (which is totally mystifying because I never touched it aside from VS automatically renewing its license) and, as an extra f-you, their recovery system claims to be unable to send a text message to my phone in order to revive the account. So VS is counting down until my license dies. Rather than make another throwaway account, which microsoft may again randomly suspend, I'd like to revert VS2019 to the 30-day trial so that VSCELicense will be able to indefinitely extend the trial.

I would greatly appreciate any guidance/instructions for how to do that.

Following some internet advice, I tried deleting all of 41717607-F34E-432C-A138-A3CFD7E25CDA and then doing a "repair" via the VS installer. This didn't work. Also, it seems to have reduced the remaining lifespan of my license by 1 day.

On a related note, one of the comments in the "VS2022 support" issue claims that VS2022 has no limitations, which I take to mean that I could simply upgrade to VS2022 and never worry about this license crap again. Is that correct?

**Comment by beatcracker** [comment]
Tbh, I don't have any VS installed right now, so I can't check, but I think that if you actually authenticated with your credentials before, it's stored on disk somewhere in your `LOCALAPPDATA` folder. AFAIK this is something that you need to delete to remove your stored account information. A quick search shows up this:

- https://developercommunity.visualstudio.com/t/appdatalocalidentityserviceaccountstorejson-is-den/990120
- https://www.koskila.net/how-to-nuke-the-identity-cache-in-visual-studio/

So you might try to delete `%LOCALAPPDATA%\.identityservice` folder and see if it helps you.

W.r.t VS 2022 - yes, it looks like it has a perpetual license built-in, but I cannot guarantee that installing it will fix your issues since you already have your credentials on disk and it might pick it up.

**Comment by ChthonVII** [comment]
Thank you very much for your reply.

Unfortunately, deleting `%LOCALAPPDATA%\.identityservice` did not work. Nor did deleting `%LOCALAPPDATA%\.identityservice` and deleting the reg key 41717607-F34E-432C-A138-A3CFD7E25CDA, and deleting privateregistry.bin, all simultaneously, and then doing a "repair" installation.

What did end up working was installing VS2022 Community. It says "product key applied," and makes no mention of my hotmail account, nor of a trial period. I guess I'll know for sure in 30 days, but it seems to be working.

The stone left unturned was doing a full uninstall and reinstall of VS2019. I didn't try that. Maybe it would have nuked the license linked to the never-used throwaway account MS randomly decided to ban.
